FROM node:20-alpine AS build
WORKDIR /repo
COPY package.json package-lock.json* ./
COPY apps ./apps
COPY libs ./libs
COPY tools ./tools
COPY tsconfig.base.json ./
COPY types ./types
ARG WORKSPACE
ARG PUBLIC_URL
ARG API_URL=http://localhost:3000
ARG REMOTE_PRODUCTS_URL=http://localhost:4201
ARG REMOTE_CART_URL=http://localhost:4202
ARG REMOTE_ORDERS_URL=http://localhost:4203
ENV PUBLIC_URL=$PUBLIC_URL
ENV API_URL=$API_URL
ENV REMOTE_PRODUCTS_URL=$REMOTE_PRODUCTS_URL
ENV REMOTE_CART_URL=$REMOTE_CART_URL
ENV REMOTE_ORDERS_URL=$REMOTE_ORDERS_URL
RUN npm install
RUN npm run build --workspace $WORKSPACE

FROM nginx:1.27-alpine
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
ARG APP_DIR
COPY --from=build /repo/apps/${APP_DIR}/dist /usr/share/nginx/html
EXPOSE 80
